USE Movies_Data_DW
GO

DROP TABLE IF EXISTS Dim_MovieData_staging

CREATE TABLE Dim_MovieData_staging (
    TITLE NVARCHAR(255),
    YEAR INT,
    IMDB_ID NVARCHAR(20),
    TYPE NVARCHAR(50),
    POSTER NVARCHAR(MAX),
    RATED NVARCHAR(10),
    RELEASED DATE,
    RUNTIME NVARCHAR(50),
    GENRE NVARCHAR(255),
    DIRECTOR NVARCHAR(255),
    WRITER NVARCHAR(MAX),
    ACTORS NVARCHAR(MAX),
    PLOT NVARCHAR(MAX),
    LANGUAGE NVARCHAR(255),
    COUNTRY NVARCHAR(255),
    AWARDS NVARCHAR(MAX),
    RATINGS NVARCHAR(MAX),
    METASCORE INT,
    IMDBRATING FLOAT,
    IMDBVOTES NVARCHAR(50),
    DVD DATE,
    BOXOFFICE NVARCHAR(255),
    PRODUCTION NVARCHAR(MAX),
    WEBSITE NVARCHAR(MAX)
);
