USE [master]
GO

/****** Object:  Database [Movies_Data_DW]    Script Date: 5/14/2023 2:56:32 PM ******/
CREATE DATABASE [Movies_Data_DW]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Movies_Data_DW', FILENAME = N'E:\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Movies_Data_DW.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Movies_Data_DW_log', FILENAME = N'E:\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Movies_Data_DW_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Movies_Data_DW].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Movies_Data_DW] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Movies_Data_DW] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Movies_Data_DW] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Movies_Data_DW] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Movies_Data_DW] SET ARITHABORT OFF 
GO

ALTER DATABASE [Movies_Data_DW] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Movies_Data_DW] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Movies_Data_DW] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Movies_Data_DW] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Movies_Data_DW] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Movies_Data_DW] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Movies_Data_DW] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Movies_Data_DW] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Movies_Data_DW] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Movies_Data_DW] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Movies_Data_DW] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Movies_Data_DW] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Movies_Data_DW] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Movies_Data_DW] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Movies_Data_DW] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Movies_Data_DW] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Movies_Data_DW] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Movies_Data_DW] SET RECOVERY FULL 
GO

ALTER DATABASE [Movies_Data_DW] SET  MULTI_USER 
GO

ALTER DATABASE [Movies_Data_DW] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Movies_Data_DW] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Movies_Data_DW] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Movies_Data_DW] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Movies_Data_DW] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Movies_Data_DW] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Movies_Data_DW] SET QUERY_STORE = ON
GO

ALTER DATABASE [Movies_Data_DW] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [Movies_Data_DW] SET  READ_WRITE 
GO


